server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: api-movie

  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672

  zipkin:
    baseUrl: http://localhost:9411/

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/movie-dev
    username: usr-movie
    password: pwd-movie
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

info:
  application:
    name: api-movie

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/